#!/bin/bash
echo "Setting variables for AWS credentials..."
export AWS_PROFILE=istio
export AWS_SHARED_CREDENTIALS_FILE=~/.aws/credentials

echo "Provisioning infrastructure..."

echo "Creating cluster sirius-b"
cd terraform/sirius-b
terraform init -input=false
terraform plan -out=/tmp/tfplan -input=false
terraform apply -input=false /tmp/tfplan
echo "Cluster sirius-b created."
cd ../..

echo "Setting kubectl configuration to use the created cluster..."
CLUSTER_REGION=$(terraform output | grep region | cut -d "=" -f 2)
CLUSTER_NAME=$(terraform output | grep cluster_name | cut -d "=" -f 2)
aws eks --region $CLUSTER_REGION update-kubeconfig --name $CLUSTER_NAME

echo "Creating cluster sirius-a"
cd terraform/sirius-a
terraform init -input=false
terraform plan -out=/tmp/tfplan -input=false
terraform apply -input=false /tmp/tfplan
echo "Cluster sirius-a created."
cd ../..

echo "Setting kubectl configuration to use the created cluster sirius-a..."
CLUSTER_REGION=$(terraform output | grep region | cut -d "=" -f 2)
CLUSTER_NAME=$(terraform output | grep cluster_name | cut -d "=" -f 2)
aws eks --region $CLUSTER_REGION update-kubeconfig --name $CLUSTER_NAME

echo "Infrastructure provisioned."
