#!/bin/bash

default_profile=default
PROFILE=${1:-$default_profile}

if [ ! -d "istio" ]
then
    curl -L https://istio.io/downloadIstio | sh -
    ISTIO_VERSION=$(curl -L -s https://api.github.com/repos/istio/istio/releases | grep tag_name | sed "s/ *\"tag_name\": *\"\\(.*\\)\",*/\\1/" | grep -v -E "(alpha|beta|rc)\.[0-9]$" | sort -t"." -k 1,1 -k 2,2 -k 3,3 -k 4,4 | tail -n 1)
    mv istio-$ISTIO_VERSION istio
    rm istio-*.tar.gz
fi

ISTIO_BIN=./istio/bin/istioctl
MANIFEST_PATH=/tmp/generated_manifest.yaml

echo "Generating manifest for istio installation..."
$ISTIO_BIN manifest generate --set profile=$PROFILE > $MANIFEST_PATH
echo "Manifest generated in $MANIFEST_PATH"

echo "Installing istio..."
$ISTIO_BIN install --set profile=$PROFILE
echo "Istio has been installed on your cluster."

echo "Verifying istio installation..."
$ISTIO_BIN verify-install -f $MANIFEST_PATH

echo "Enabling automatic injection of envoy sidecar proxy when deploying applications."
kubectl label namespace default istio-injection=enabled
